### PR TITLE
update ngx-progressive-image-loader

### PR DESCRIPTION
**Pull request by maxisam**
I have tested this version. It built on my local machine

### CODE REVIEW

**Comment by Ismaestro** [comment]
Hi!

Finally I had tu add a validation to show if it's browser or not depending on the platformId, you can see it [here](https://github.com/Ismaestro/angular8-example-app/blob/5364f1e745f989f785bebf6c90925118f358692b/src/app/shared/components/hero-card/hero-card.component.html#L24) and [here](https://github.com/Ismaestro/angular8-example-app/blob/5364f1e745f989f785bebf6c90925118f358692b/src/app/shared/components/hero-card/hero-card.component.ts#L38).

BR

**Comment by maxisam** [comment]
Weird. But it works without the code you added. Have you installed the new version?

**Comment by Ismaestro** [comment]
Yes the current version is [4.0.0-beta.15](https://github.com/Ismaestro/angular8-example-app/blob/4db0021e7107c7c3ca6ef37d3dc2027777642c7a/package.json#L64).

**Comment by Ismaestro** [comment]
Maybe you can test it by yourself and see if it hapends to you. The steps to reproduce are simple:
1. Remove  *ngIf="isBrowser" sentence.
2. Run ```
npm run build:ssr && npm run serve:ssr```
3. Go to localhost:4000

Then I see:
```
Node server listening on http://localhost:4000
Angular library has started with this options:  { config: { say: 'hello' } }
fetched heroes
fetched heroes
/Users/iramos/WebstormProjects/angular7-example-app/node_modules/zone.js/dist/zone-node.js:199
                        throw error;
                        ^

TypeError: Cannot read property 'src' of undefined
    at loadImage (/Users/iramos/WebstormProjects/angular7-example-app/node_modules/ngx-progressive-image-loader/bundles/ngx-progressive-image-loader.umd.js:147:31)
    at ProgressiveImageDirective.ngOnInit (/Users/iramos/WebstormProjects/angular7-example-app/node_modules/ngx-progressive-image-loader/bundles/ngx-progressive-image-loader.umd.js:501:21)
    at checkAndUpdateDirectiveInline (/Users/iramos/WebstormProjects/angular7-example-app/node_modules/@angular/core/bundles/core.umd.js:19372:23)
    at checkAndUpdateNodeInline (/Users/iramos/WebstormProjects/angular7-example-app/node_modules/@angular/core/bundles/core.umd.js:27606:24)
    at checkAndUpdateNode (/Users/iramos/WebstormProjects/angular7-example-app/node_modules/@angular/core/bundles/core.umd.js:27568:20)
```

**Pull request closed without merging**
